kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo-configmap
  namespace: default
data:
  host: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-express
  namespace: default
  labels:
    app:  mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongo-express
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mongo-express
        image:  mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: host
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
              secretKeyRef:
                name:  mongo-secret
                key:  username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
        ports:
        - containerPort:  8081
          name:  mongo-express
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: default
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
  - name: mongo-express
    protocol: TCP
    port: 80
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - mongo.edx.ithut.cloud
    secretName: mongoexpress-tls
  ingressClassName: nginx
  rules:
  - host: mongo.edx.ithut.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 80