
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://runatlantis.github.io/helm-charts'
    targetRevision: 4.25.0
    helm:
      values: |-
        github:
          user: foo
          token: bar
          secret: test
    chart: atlantis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
