apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"     # Sync wave annotation to ensure the minimum time between syncs
    argocd.argoproj.io/sync-options: "--sync-wait 60"  # Sync options annotation to set the sync wait time to 60 seconds
spec:
  project: default
  source:
    repoURL: https://github.com/zeeshan-maqbool/argocd
    targetRevision: HEAD # or specify a specific commit hash or branch/tag name
    path: argocd/apps/mongo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
